package ai.ecma.appstaff.enums;

import lombok.Getter;

/**
 * CUSTOM FIELDLAR UCHUN MAHSUS TYPELAR.
 * TIZIMGA QO'SHILGAN BARCHA CUSTOM FIELDLAR AYNAN SHU TYPELARDAN BIRI BO'LISHI KERAK
 */
@Getter
public enum CustomFieldTypeEnum {

    // SELECTLAR UCHUN ISHLATILADI
    // FRONTENDCHI SHUNGA QARAB SELECT CHIQARADI
    DROPDOWN("dropdown"),

    // RATINGLARNI BELGILASH UCHUN ISHLATILADI
    // MASALAN: YULDUZCHALAR BO'LISHI MUMKIN
    // FRONTENDCHI SHUNGA QARAB EMOJI CHIQARADI
    RATING("rating"),

    // MULTI SELECT
    // FRONTENDCHI SHUNGA QARAB MULTI SELECT CHIQARADI
    LABELS("labels"),

    // UZUN TEXTLAR UCHUN
    // MASALAN: DESCRIPTIONLAR UCHUN
    // FRONTENDCHI SHUNGA QARAB DESCRIPTION UCHUN KATTAROQ INPUT CHIQARADI
    LONG_TEXT("long_text"),

    // QISQA TEXTLAR UCHUN
    // MASALAN: ISMI, FAMILIYASI
    // FRONTENDCHI SHUNGA QARAB INPUT CHIQARADI
    SHORT_TEXT("short_text"),


    ENUM_DROPDOWN("enum_dropdown"),

    PRIORITY("priority"),

    //
    // FRONTENDCHI SHUNGA QARAB CHECKBOX CHIQARADI
    CHECKBOX("checkbox"),

    // EMAILNI SAQLASH UCHUN TYPE
    // FRONTENDCHI SHUNGA QARAB EMAIL UCHUN MAHSUS INPUT CHIQARADI VA KO'RINISHINI HAMSHUNGA QARAB TO'G'IRLAYDI
    EMAIL("email"),

    // FILELARNI SAQLASH UCHUN TYPE
    // FRONTENDCHI SHUNGA QARAB FILELARNI KO'RSATADI
    FILES("files"),

    // TELEFON RAQAMNI SAQLASH UCHUN TYPE
    // FRONTENDCHI SHUNGA QARAB TELEFON RAQAMLARNI KO'RSATADI (oddiy raqamlardan farqli qilib)
    PHONE("phone"),

    // NUMBER (INTEGER, LONG) LARNI SAQLASH UCHUN TYPE
    // FRONTENDCHI BUNI RAQAMLIGINI BILADI
    NUMBER("number"),

    // PUL QIYMATLARINI SAQLASH UCHUN TYPE
    // FRONTENDCHI PULNI KO'RSATISH KERAKLIGINI BILADI
    MONEY("money"),

    // SANALARNI SAQLASH UCHUN TYPE
    // FRONTENDCHI SANANI KO'RSATISH KERAKLIGINI BILADI
    DATE("date"),

    TIME("time"),

    // TREE ICHMA ICH TUGANMAS TREE BO'LIB KETADIGAN MA'LUMOTLARNI SAQLASH UCHUN TYPE
    //
    TREE("tree"),


    SPECIAL_LABEL("super_label"),//COMMENTS GA O'XSHAGAN DATA DA ID LAR LISTI KETADI

    //SALES DA KERAK FAQAT BOSHQA JOYDA KERAGI YO'Q
    CALL("call"),
    MESSAGE("message"),
    CALL_DURATION("call_duration"),


    //=======================================================
    //CALL YOKI SUPERLABEL TURI UCHUN KERAK HTTP_METHOD DOIM POST BO'LADI
    CALL_TYPE("call_type"),
    CALL_STATUS("call_status"),


    INPUT_SELECT_DROPDOWN("input_select_dropdown"), DATE_TIME("date_time"), ENUM_LABELS("enum_labels"),


    //TURNIKET UCHUN FAQAT
    TURNIKET_DAY("turniket_day")


    ;

    private final String title;

    CustomFieldTypeEnum(String title) {
        this.title = title;
    }
}
