package ai.ecma.appstaff.enums;

// HODIMNING STATUSLARI. TIZIMDAGI HOLATI
public enum EmployerStatusEnum {

    // HALI TO'LIQ TIZIMGA QO'SHILMAGAN HODIM. BU HODIM TIZIM UCHUN YO'Q
    DRAFT,

    // HOZIRDA ISHLAB TURGAN HODIM
    WORKING,

    //ISHDAN BO'SHATILGAN HODIM
    RESIGNATION
}
