package ai.ecma.appstaff.enums;

public enum EntityFieldNameEnum {
    //  COMPLETED
    DEPARTMENT_NAME,
    DEPARTMENT_ACTIVE,
    //  COMPLETED
    EMPLOYEE_FIRST_NAME,
    EMPLOYEE_LAST_NAME,
    EMPLOYEE_MIDDLE_NAME,
    EMPLOYEE_PHOTO_URL,
    EMPLOYEE_BIRTH_DATE,
    EMPLOYEE_MARITAL_STATUS,
    EMPLOYEE_GENDER,
    EMPLOYEE_EMAIL,
    EMPLOYEE_PASSPORT_SERIAL,
    EMPLOYEE_PASSPORT_NUMBER,
    EMPLOYEE_PASSPORT_GIVEN_ORGANISATION,
    EMPLOYEE_PASSPORT_GIVEN_DATE,
    EMPLOYEE_PASSPORT_EXPIRE_DATE,
    EMPLOYEE_PASSPORT_PERMANENT_ADDRESS,
    EMPLOYEE_PASSPORT_CURRENT_ADDRESS,
    EMPLOYEE_PERSONAL_NUMBER,
    //    ...
    //  COMPLETED
    EMPLOYEE_ATTACHMENT_FILE_URL,
    EMPLOYEE_ATTACHMENT_DESCRIPTION,
    //  COMPLETED
    EMPLOYEE_ATTENDANCE_ATTENDANCE,
    EMPLOYEE_ATTENDANCE_WORK_HOUR,
    //  COMPLETED
    EMPLOYEE_CATEGORY_DEPARTMENT,
    EMPLOYEE_CATEGORY_POSITION,
    EMPLOYEE_CATEGORY_EMPLOYEE_CATEGORY_TYPE,
    EMPLOYEE_CATEGORY_REQUIREMENT,
    EMPLOYEE_CATEGORY_DESCRIPTION,
    EMPLOYEE_CATEGORY_ACTIVE,
    //
    EMPLOYEE_CATEGORY_TYPE,
    //
    EMPLOYEE_EDUCATION_HISTORY,
    //
    EMPLOYEE_EXPERIENCE_HISTORY,
    //
    EMPLOYEE_PHONE_NUMBER,
    //
    EMPLOYMENT_INFO,
    //
    HOLIDAY,
    //
    POSITION,
    //
    PRIVILEGE_TYPE,
    //
    STATE,
    //
    TimeSheet,
    //
    TimeSheet_EMPLOYEE,
    //
    TARIFF_GRID,
    //
    TEMPLATE_FOR_SICK,
    //
    WORK_DAY, POSITION_DEPARTMENT, POSITION_NAME, POSITION_ACTIVE, PRIVILEGE_TYPE_NAME, PRIVILEGE_TYPE_ACTIVE, SKILL_NAME, SKILL_COLOR, SKILL_ACTIVE, TARIFF_GRID_DEPARTMENT, TARIFF_GRID_POSITION, TARIFF_GRID_BRANCH, TARIFF_GRID_EMPLOYEE_CATEGORY, TARIFF_GRID_PAYMENT_CRITERIA, TARIFF_GRID_PAYMENT_AMOUNT, TARIFF_GRID_DAY, TARIFF_GRID_HOUR, TARIFF_GRID_ACTIVE, TARIFF_GRID_DAY_AMOUNT, TARIFF_GRID_HOUR_AMOUNT, TARIFF_GRID_BONUS_TYPE_AMOUNT, TARIFF_GRID_BONUS_PERCENT, TEMPLATE_FOR_SICK_PRIVILEGE, TEMPLATE_FOR_SICK_PRIVILEGE_TYPE, TEMPLATE_FOR_SICK_FROM_COUNT, TEMPLATE_FOR_SICK_TO_COUNT, TEMPLATE_FOR_SICK_PERCENT, TEMPLATE_FOR_SICK_ACTIVE,
}
