package ai.ecma.appstaff.enums;

public enum EntityColumnMapValuesKeyEnum {

    TYPE,//COLUMNNING QAYSI TYPE DA EKANLIGI. MONEY, SHORT_TEXT, DROPDOWN

    OTHER_SERVICE,//TURGAN ENTITYMIZDA ULANGAN ID BOSHQA MICROSERVICE DA

    SUM,//QACHONKI BERILGAN COLUMNNI YIG'INDISINI HISOBLASH KERAK BO'LGANDA

    //QACHONKI BERILGAN COLUMN BELGILANGAN ENTITYDA NECHA MAROTABA ROW SIZFATIDA YOZILGANLIGI
    COUNT,

    //O'ZIMIZ TURGAN ENTITYDAGI QAYSIDIR FIELD FOREIGN KEY BO'LGANDA, QAYSI TABLE BILAN ULANGANLIGI
    FOREIGN_TABLE,

    //O'ZIMIZ TURGAN ENTITYDAGI QAYSIDIR FIELD FOREIGN KEY BO'LGANDA,ULANGAN TABLENI ID SI BIZDA QAYSI COLUMN NAME I(REGION TABLE BIZGA ULANGAN BOLSA FOREIGN_TABLE_ID=REGION_ID)
    FOREIGN_TABLE_ID,

    //TURGAN ENTITYIMZGA ULANGAN ENTITYNING QAYSI COLUMN BO'YICHA SORT QILISHIMIZ,
    ORDERING_COLUMN,

    //TURGAN ENTITYIMZGA ULANGAN ENTITYNING QAYSI COLUMN BO'YICHA SERCH QILISHIMIZ
    SEARCHING_COLUMN,

    //TURGAN ENTITYMIZGA ULANGAN ENTITYNING ICHIDAGI BOSHQA BIR ENTITYNING FIELDLARINI OLISH UCHUN   //EMPLOYMENT_INFO
    RELATIONAL_TABLE,

    //TURGAN ENTITYMIZGA ULANGAN ENTITYNING ID SINING NOMI //EMPLOYMENT_INFO_ID
    RELATIONAL_TABLE_ID,

    //TURGAN ENTITYMIZGA ULANGAN ENTITYNING ICHIDAGI BOSHQA BIR ENTITYNING NAME SI   //EMPLOYEE
    RELATIONAL_TABLE_FOREIGN_TABLE,

    //TURGAN ENTITYMIZGA ULANGAN ENTITYNING ICHIDAGI BOSHQA BIR ENTITYNING ID SI   //EMPLOYEE_ID
    RELATIONAL_TABLE_FOREIGN_TABLE_ID,

    //TURGAN ENTITYMIZGA ULANGAN ENTITYNING ICHIDAGI BOSHQA BIR ENTITYDAGI QIDIRILYOTGAN COLUMN_NAME  //EMPLOYEE NING FIRST_NAME
    RELATIONAL_TABLE_FOREIGN_TABLE_COLUMN,


    //BIZ TURGAN ENTITY VA BOG'LANGAN ENTITY UCHUN O'RTADA 3 TABLE OCHILGANDA, MISOL UCHUN HUMAN VA COURSE BOG'LAYDIGAN HUMAN_COURSE TABLE
    OTHER_TABLE,

    //BIZ QIDIRAYOTGAN TABLEDA QAYSI ENTITY UCHUN QUERY YOZAYOTGAN BO'LSAK,
    // O'SHA ENTITY NING ID SI QIDIRILAYOTGAN TABLEDA QANDAY NOM BILAN NOMLANGANLIGI
    // (MISOL UCHUN BIZ HUMAN ENEITY SI UCHUN QUERY YOZYAPMIZ, SHUNDA HUMAN_COURSE
    // ENTITY SIDAN HUMAN ENTITY SINING ID FIELDI QANDAY NOMALANGANLIGI (human_id))
    IN_OTHER_TABLE_THIS_TABLES_ID_NAME,

    //BIZ QIDIRAYOTGAN TABLEDA QAYSI ENTITY UCHUN QUERY YOZAYOTGAN BO'LSAK
    // O'SHA O'SHA ENTITY BILAN BIRGA BOG'LANGAN RNRITYNING ID  SI QIDIRILAYOTGAN TABLEDA QANDAY NOM BILAN NOMLANGAN
    // (MISOL UCHUN BIZ HUMAN ENEITY SI UCHUN QUERY YOZYAPMIZ, SHUNDA HUMAN_COURSE
    //  ENTITY SIDAN COURSE ENTITY SINING ID FIELDI QANDAY NOMALANGANLIGI (course_id))
    IN_OTHER_TABLE_SEARCHING_COLUMN_NAME,

    //O'ZIMIZ TURGAN ENTITYDAGI ID FIELDIMIZ QAYSIDIR ENTITYDA FOREIGN KEY BO'LGANDA, QAYSI TABLE NING ICHIDA BIZNING ID BORLIGI
    DIRECTIONAL_FOREIGN_TABLE,

    //O'ZIMIZ TURGAN ENTITYNI ID FIELD BOSHQA ENTITY BILAN ULANGANDA O'SHA ENTITYNING QAYSIDIRI COLUMN BO'YICHA AGREGATE FUNCTIONLARNI ISHLATISHIMIZ UCHUN
    DIRECTIONAL_COLUMN,

    //BOSHQA TABLEDA BIZNING ID QAYSI COLUMN DA TURGANLIGI
    DIRECTIONAL_OURS_COLUMN,

    //BU VIEW_COLUMN GA KIMDIR TEGA OLADIMI, MASALAN TO'LOV LAR COLUMNINI HECH KIM O'ZGARTIRA OLMAYDI, QIYMATLARI YES, NO
    ENABLED,


    //==================FILTER, SEARCH, SORT============
    FILTERABLE,//SHU COLUMN DA FILTER QILAOLADIMI
    SEARCHABLE,//SHU COLUMN DA SEARCH QILAOLADIMI
    SORTABLE,//SHU COLUMN DA SORT QILAOLADIMI
    ROOT, // SHU COLUMNNI HIDE=TRUE QILISH MUMKIN EMAS

    // SHOW COLUMN FALSE BOLSA BU COLUMN  VIEW NI HECH QAYERIDA KO'RINMAYDI.
    SHOW_COLUMN,

    //=======================================================
    //CALL YOKI SUPERLABEL TURI UCHUN KERAK HTTP_METHOD DOIM POST BO'LADI
    CALL_TARGET_COLUMN, //BU AGAR CALL BOSILSA MISOL UCHUN LEAD NING QAYSI COLUMNINI DESTINATION NUMBER SIFATIDA OLIB KETISHINI BELGILAYDI
    REQUEST_URL, //QAYSI API GA REQUEST KETISHI

    MIN,
    MAX,
    FUNCTIONAL_OPERATION,


    // BU GENERIC VEIW DA QAYTGAN ID LINI SUM QIYMATLARINI YIGIB BERADI
    // TABLE_VIEW DA COLUMNLARNIDAGI BARCHA SUMMA NI YIG'IB BERISH UCHUN
    INLINE_SUM,

    //USHBU FEILD MAVJUD BOLGAN COLUMN BOSHQA SERVICEDAN DATA OLISHI KERAK. VA UNI TYPE i SHORT TEXT BOLADI(TYPE LABELS VA DROP_DOWN BOLMAYDI VA UNI SHAPKASIDA HECH NIMA KETMAYDI)
    NOT_FROM_DB

}
