package ai.ecma.appstaff.enums;

public enum EntityNameEnum {
    DEPARTMENT,
    EMPLOYEE,
    EMPLOYEE_ATTACHMENT,
    EMPLOYEE_ATTENDANCE,
    EMPLOYEE_CATEGORY,
    EMPLOYEE_CATEGORY_TYPE,
    EMPLOYEE_EDUCATION_HISTORY,
    EMPLOYEE_EXPERIENCE_HISTORY,
    EMPLOYEE_PHONE_NUMBER,
    EMPLOYMENT_INFO,
    HOLIDAY,
    POSITION,
    PRIVILEGE_TYPE,
    STATE,
    TimeSheet,
    TimeSheet_EMPLOYEE,
    TARIFF_GRID,
    TEMPLATE_FOR_SICK,
    WORK_DAY, SKILL,
}
