package ai.ecma.appstaff.enums;

// HODIMLARNING TA'LIM DARAJALARI
public enum StudyDegreeEnum {
    //TODO TO'LIQ YOZIB CHIQISH KERAK TUSHUNARLI QILIB. O'ZBEKISTON UCHUN
    PROFESSIONAL,
    UNDERGRADUATE,
    TRANSFER,
    ASSOCIATE,
    BACHELOR,
    GRADUATE,
    MASTER,
    DOCTORAL
}
